### ISSUE TITLE
Kubernetes Cluster "OS and Data Disks Encrypted with CMK" and "Temp Disks and Cache Not Encrypted.md" False Positive

### ISSUE THREAD

**Issue by fgomesz** [turbot/steampipe-mod-azure-compliance#134] opened 2022-10-13 13:07 UTC
**Describe the bug**
When the Kubernetes cluster has a whitelist of IP addresses and the steampipe tool is not whitelisted, the field "disk_encryption_set_id" from the table "azure_kubernetes_cluster" is null. In turn, the disks are encrypted, but steampipe is not whitelisted, which can lead to false positives.

**Steampipe version (`steampipe -v`)**
Example: v0.16.4

**Plugin version (`steampipe plugin list`)**
+--------------------------------------------------+---------+-------------+
| Name                                             | Version | Connections |
+--------------------------------------------------+---------+-------------+
| hub.steampipe.io/plugins/turbot/aws@latest       | 0.77.0  | aws         |
| hub.steampipe.io/plugins/turbot/azure@latest     | 0.32.0  | azure       |
| hub.steampipe.io/plugins/turbot/azuread@latest   | 0.6.0   | azuread     |
| hub.steampipe.io/plugins/turbot/steampipe@latest | 0.5.0   | steampipe   |
+--------------------------------------------------+---------+-------------+

**To reproduce**
Enforce IP whitelisting on Kubernetes clusters, do not whitelist the IP address of steampipe and encrypt the disks of Kubernetes cluster.

**Expected behavior**
[A clear and concise description of what you expected to happen.]
The control (https://hub.steampipe.io/mods/turbot/azure_compliance/queries/kubernetes_cluster_os_and_data_disks_encrypted_with_cmk) will mention that the Kubernetes cluster is not encrypted, which is not true.
I know that the easy solution is to whitelist steampipe, but maybe it is possible to provide a way to know if the "disk_encryption_set_id" is null because the Steampipe is not whitelisted or because there really is no encryption. Thank you for your time

**Additional context**
(https://hub.steampipe.io/mods/turbot/azure_compliance/queries/kubernetes_cluster_os_and_data_disks_encrypted_with_cmk)

**Comment by misraved** [comment] 2022-10-13 13:15
Thanks @fgomesz for raising this issue and providing good context on how the control should work.

We will pick this up shortly and hopefully fix and release it 👍 .

**Comment by bigdatasourav** [comment] 2023-06-13 06:02
@fgomesz We apologize for the delayed response and any inconvenience caused. We appreciate your patience throughout this process.

After a thorough investigation, we regret to inform you that we have been unable to reproduce the above issue. We understand that this discrepancy may be frustrating for you.

However, please be assured that we take such reports seriously and are committed to ensuring the accuracy of our compliance checks. Although we are closing the issue for now due to our inability to reproduce it, we will continue to look into this matter further.

If you come across any additional information, specific configurations, or steps to reproduce the issue, please do not hesitate to provide them. Your input will greatly assist us in our ongoing investigation and efforts to resolve the matter.

Once again, we apologize for any inconvenience caused. We appreciate your understanding, and please rest assured that we remain dedicated to improving our services and addressing any potential issues that may arise.

Thank you for your understanding and cooperation.

**Comment by cbruno10** [comment] 2023-06-13 17:29
@bigdatasourav Is this something we can fix in the plugin, so the `azure_kubernetes_cluster` table can return the correct disk encryption information even if Steampipe is not whitelisted?

Else, are we able to detect if we're getting a response as if we're not whitelisted, so we can return the correct result in the query?

**Comment by bigdatasourav** [comment] 2023-06-14 06:10
@cbruno10 @fgomesz We get the disk encryption information even if Steampipe is not whitelisted.

Below are the steps we have followed to reproduce the above issue- 

1. Created a cluster name test-cmk1 with disk-encryption-set and without enforcing the IP whitelist - 
<img width="753" alt="image" src="https://github.com/turbot/steampipe-mod-azure-compliance/assets/78197905/f52bcdcd-8803-4399-a6ba-ce2c0a21d6dc">


<img width="828" alt="image" src="https://github.com/turbot/steampipe-mod-azure-compliance/assets/78197905/75b4d22d-0ac1-4ba3-9c8a-c9c4d58941dc">

```
> select name, disk_encryption_set_id from azure_kubernetes_cluster where name = 'test-cmk1'
+-----------+--------------------------------------------------------------------------------------------------------------------------------------+
| name      | disk_encryption_set_id                                                                                                               |
+-----------+--------------------------------------------------------------------------------------------------------------------------------------+
| test-cmk1 | /subscriptions/d46d7416-f95f-4771-454354354/resourceGroups/demo/providers/Microsoft.Compute/diskEncryptionSets/test-cmk-disk |
+-----------+--------------------------------------------------------------------------------------------------------------------------------------+
```

Control output - (expected)
```
➜  steampipe-mod-azure-compliance git:(main) steampipe query azure_compliance.query.kubernetes_cluster_os_and_data_disks_encrypted_with_cmk
+---------------------------------------------------------------------------------------------------------------------------------------------+--------+------------------------------------------------------+----------------+-----------------+
| resource                                                                                                                                    | status | reason                                               | resource_group | subscription    |
+---------------------------------------------------------------------------------------------------------------------------------------------+--------+------------------------------------------------------+----------------+-----------------+
| /subscriptions/d46d7416-f95f-4771-454354354/resourcegroups/demo/providers/Microsoft.ContainerService/managedClusters/test-cmk1      | ok     | test-cmk1 os and data diska encrypted with CMK.      | demo           | new AAA |
```

2. Created a cluster name test-whitelist with disk-encryption-set and enforced the IP whitelist - (Steampipe is not whitelisted)
<img width="755" alt="image" src="https://github.com/turbot/steampipe-mod-azure-compliance/assets/78197905/6a3be6c7-28c7-4a73-bd92-81ab7eeaea85">

<img width="847" alt="image" src="https://github.com/turbot/steampipe-mod-azure-compliance/assets/78197905/2743779b-ff35-4ce2-8d35-b395addec54d">

```
> select name, disk_encryption_set_id from azure_kubernetes_cluster where name = 'test-whitelist'
+----------------+--------------------------------------------------------------------------------------------------------------------------------------+
| name           | disk_encryption_set_id                                                                                                               |
+----------------+--------------------------------------------------------------------------------------------------------------------------------------+
| test-whitelist | /subscriptions/d46d7416-f95f-471-bbb5-529d4c769c/resourceGroups/demo/providers/Microsoft.Compute/diskEncryptionSets/test-cmk-disk |
+----------------+--------------------------------------------------------------------------------------------------------------------------------------+
```

Control output - (expected)
```
➜  steampipe-mod-azure-compliance git:(main) steampipe query azure_compliance.query.kubernetes_cluster_os_and_data_disks_encrypted_with_cmk
+---------------------------------------------------------------------------------------------------------------------------------------------+--------+------------------------------------------------------+----------------+-----------------+
| resource                                                                                                                                    | status | reason                                               | resource_group | subscription    |
+---------------------------------------------------------------------------------------------------------------------------------------------+--------+------------------------------------------------------+----------------+-----------------+
| /subscriptions/d46d7416-f95f-4771-bbb5-529d4c76659c/resourcegroups/demo/providers/Microsoft.ContainerService/managedClusters/test-whitelist | ok     | test-whitelist os and data diska encrypted with CMK. | demo           | newwarriors AAA |
+---------------------------------------------------------------------------------------------------------------------------------------------+--------+-----------------------------------
```

Please let us know if we miss anything.

**Comment by bigdatasourav** [comment] 2023-06-21 08:59
We are closing this issue because we haven't heard from you yet. Please feel free to reopen the issue if you want to share or discuss anything.

**Closed by bigdatasourav** 2023-06-21 08:59 UTC
Labels: bug
